spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@test14-database:27017/test14-app?authSource=admin
      #database: test14-app
springdoc:
  api-docs:
    path: /openapi

app:
  base:
    url: "http://localhost:8080"